ALTER TABLE project_resources
    DROP CONSTRAINT IF EXISTS project_resources_category_check;

ALTER TABLE project_resources
    ADD CONSTRAINT project_resources_category_check
    CHECK (category IN (
        'Design',
        'Engineering',
        'Product',
        'Testing',
        'Meetings',
        'Analytics',
        'Documentation',
        'Research',
        'Marketing',
        'Sales',
        'Customer Support',
        'Operations',
        'Finance',
        'Legal',
        'Human Resources',
        'Recruiting',
        'Strategy',
        'Planning',
        'Roadmaps',
        'Requirements',
        'Specifications',
        'Architecture',
        'APIs & Integrations',
        'Code Repositories',
        'DevOps',
        'Cybersecurity',
        'Data Science',
        'Databases',
        'Infrastructure',
        'Deployment',
        'Monitoring',
        'Incident Response',
        'Quality Assurance',
        'Bug Tracking',
        'User Experience',
        'Prototyping',
        'Branding',
        'Content',
        'SEO',
        'Social Media',
        'Campaigns',
        'Competitor Analysis',
        'Training',
        'Onboarding',
        'Policies',
        'Contracts',
        'Vendor Management',
        'Reports',
        'Presentations',
        'Other'
    ));
